
db.url=jdbc:mysql://localhost:3306/easebuzz_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC

db.username=root
db.password=Welcome@123456
db.driver=com.mysql.cj.jdbc.Driver

# Easebuzz Payment Gateway Configuration
easebuzz.key=UDHDLP4PK
easebuzz.salt=QWMS4X1QJ

# AES Encryption Configuration
aes.secret.key=12345678901234567890123456789012


